# Generated by Django 5.0 on 2023-12-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('review', models.CharField(max_length=100, verbose_name='review')),
                ('describtion', models.TextField(verbose_name='describtion')),
                ('enerjy', models.IntegerField(verbose_name='enerjy')),
                ('materials', models.ManyToManyField(to='recipe_api.material')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='recipes',
            field=models.ManyToManyField(to='recipe_api.recipe'),
        ),
    ]
